import Image from "next/image";
import { ArrowDown, ArrowRight, BriefcaseBusiness, Cloud, Code2, Container, GraduationCap, MapPin, Workflow, Activity } from "lucide-react";
import { siteConfig } from "@/src/config/site";
import { technologyGroups, type Locale } from "@/src/data/translations";

type Content = (typeof import("@/src/data/translations").translations)[Locale];

export function Hero({ t }: { t: Content }) {
  return <section id="home" className="dark-section relative flex min-h-[690px] items-center overflow-hidden pb-12 pt-28 sm:min-h-[720px]"><div className="pointer-events-none absolute inset-0 opacity-30" style={{ backgroundImage: "radial-gradient(circle at 75% 45%, rgba(37,99,235,.25), transparent 32%), linear-gradient(rgba(148,163,184,.07) 1px, transparent 1px), linear-gradient(90deg, rgba(148,163,184,.07) 1px, transparent 1px)", backgroundSize: "auto, 52px 52px, 52px 52px" }} /><div className="container-shell relative grid items-center gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="max-w-xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-blue-400/20 bg-blue-400/10 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[.18em] text-blue-200"><span className="h-1.5 w-1.5 rounded-full bg-blue-400" />{t.hero.eyebrow}</div><p className="mb-2 text-lg font-medium text-slate-300">{t.hero.greeting}</p><h1 className="text-[clamp(3.25rem,7vw,5.6rem)] font-bold leading-[.98] tracking-[-.065em] text-white">Jorge <span className="text-blue-400">Gallardo</span></h1><p className="mt-5 text-xl font-medium text-blue-100">{t.hero.role}</p><p className="mt-4 max-w-md text-base leading-7 text-slate-300">{t.hero.description}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#projects" className="focus-underline inline-flex min-h-12 items-center gap-2 rounded-lg bg-blue-600 px-5 text-sm font-semibold text-white shadow-lg shadow-blue-950/30 transition hover:-translate-y-0.5 hover:bg-blue-500">{t.hero.projects}<ArrowDown size={16} /></a>{siteConfig.links.github && <a href={siteConfig.links.github} target="_blank" rel="noopener noreferrer" className="focus-underline inline-flex min-h-12 items-center gap-2 rounded-lg px-4 text-sm font-medium text-white transition hover:bg-white/5"><i className="devicon-github-original technology-icon" aria-hidden="true" />{t.hero.github}</a>}{siteConfig.links.linkedin && <a href={siteConfig.links.linkedin} target="_blank" rel="noopener noreferrer" className="focus-underline inline-flex min-h-12 items-center gap-2 rounded-lg px-4 text-sm font-medium text-white transition hover:bg-white/5"><i className="devicon-linkedin-plain technology-icon" aria-hidden="true" />{t.hero.linkedin}</a>}</div></div><div className="relative mx-auto w-full max-w-[590px] lg:-mr-7"><div className="absolute inset-[15%] rounded-full bg-blue-500/10 blur-3xl" /><Image src="/assets/hero-devops.png" alt="" width={1250} height={900} priority className="relative h-auto w-full object-contain" sizes="(max-width: 1024px) 90vw, 52vw" /></div></div></section>;
}

export function About({ t }: { t: Content }) {
  const facts = [
    { Icon: GraduationCap, title: t.about.degree, detail: t.about.specialization },
    { Icon: BriefcaseBusiness, title: t.about.cloud },
    { Icon: Code2, title: t.about.development },
    { Icon: MapPin, title: t.about.location },
  ];
  return <section id="about" className="section-space"><div className="container-shell"><div className="grid items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="mb-3 text-sm font-semibold uppercase tracking-[.15em] text-blue-600">01 / {t.about.title}</p><h2 className="section-title">{t.about.title}</h2><p className="section-lead max-w-2xl">{t.about.intro}</p><p className="section-lead max-w-2xl">{t.about.second}</p></div><div className="card-surface divide-y divide-slate-100 px-5 sm:px-7">{facts.map(({ Icon, title, detail }) => <div key={title} className="flex items-center gap-4 py-5"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon size={21} /></span><div><p className="text-sm font-semibold text-slate-800">{title}</p>{detail && <p className="mt-1 text-sm text-slate-500">{detail}</p>}</div></div>)}</div></div></div></section>;
}

export function Expertise({ t }: { t: Content }) {
  const icons = [Cloud, Workflow, Code2, Container, Activity, Code2];
  return <section id="expertise" className="section-space bg-slate-50"><div className="container-shell"><div className="mb-10"><p className="mb-3 text-sm font-semibold uppercase tracking-[.15em] text-blue-600">02 / {t.expertise.title}</p><h2 className="section-title">{t.expertise.title}</h2><p className="section-lead">{t.expertise.lead}</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{t.expertise.items.map(([title, description], index) => { const Icon = icons[index]; return <article key={title} className="card-surface group p-6 transition duration-200 hover:-translate-y-1 hover:shadow-md"><span className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600 transition group-hover:bg-blue-600 group-hover:text-white"><Icon size={21} /></span><h3 className="text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>; })}</div></div></section>;
}

export function Technologies({ t }: { t: Content }) {
  return <section id="skills" className="section-space"><div className="container-shell"><div className="mb-10"><p className="mb-3 text-sm font-semibold uppercase tracking-[.15em] text-blue-600">03 / {t.technologies.title}</p><h2 className="section-title">{t.technologies.title}</h2><p className="section-lead">{t.technologies.lead}</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{technologyGroups.map((group, index) => <article key={t.technologies.groups[index]} className="card-surface p-5 sm:p-6"><h3 className="mb-5 text-sm font-semibold text-slate-800">{t.technologies.groups[index]}</h3><ul className="grid grid-cols-3 gap-x-2 gap-y-5">{group.map((technology) => <li key={technology.name} className="flex min-w-0 flex-col items-center gap-2 text-center text-xs leading-4 text-slate-600"><Image src={technology.icon} alt="" aria-hidden="true" width={32} height={32} className="h-8 w-8 shrink-0 object-contain" /><span>{technology.name}</span></li>)}</ul></article>)}</div></div></section>;
}

function ProjectCard({ title, subtitle, description, image, alt, technologies, href, action }: { title: string; subtitle: string; description: string; image: string; alt: string; technologies: string[]; href: string; action: string }) {
  return <article className="group overflow-hidden rounded-2xl border border-white/10 bg-[#101b2b] transition duration-200 hover:-translate-y-1 hover:border-blue-400/30 hover:shadow-xl hover:shadow-black/20"><div className="relative flex h-[255px] items-center justify-center overflow-hidden bg-[#111d2e] px-4 pt-5 sm:h-[290px]"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: "radial-gradient(ellipse at 70% 65%, rgba(37,99,235,.25), transparent 50%)" }} /><Image src={image} alt={alt} width={900} height={650} className="relative h-full w-full object-contain transition duration-300 group-hover:scale-[1.025]" sizes="(max-width: 640px) 90vw, (max-width: 1024px) 45vw, 34vw" /></div><div className="p-6 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[.13em] text-blue-300">{subtitle}</p><h3 className="mt-2 text-2xl font-semibold tracking-tight text-white">{title}</h3><p className="mt-3 min-h-[72px] text-sm leading-6 text-slate-300">{description}</p><ul className="mt-5 flex flex-wrap gap-2">{technologies.map((technology) => <li key={technology} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-300">{technology}</li>)}</ul>{href && <a href={href} target="_blank" rel="noopener noreferrer" className="focus-underline mt-6 inline-flex items-center gap-2 rounded text-sm font-semibold text-blue-300 transition hover:text-white">{action}<ArrowRight size={16} /></a>}</div></article>;
}

export function Projects({ t }: { t: Content }) {
  return <section id="projects" className="dark-section section-space"><div className="container-shell"><div className="mb-10"><p className="mb-3 text-sm font-semibold uppercase tracking-[.15em] text-blue-300">04 / {t.projects.title}</p><h2 className="section-title">{t.projects.title}</h2><p className="section-lead">{t.projects.lead}</p></div><div className="grid gap-5 lg:grid-cols-2"><ProjectCard title="ScrambleTimer" subtitle={t.projects.scrambleTitle} description={t.projects.scrambleBody} image="/assets/scrambletimer-macbook.png" alt={t.projects.scrambleAlt} technologies={["Next.js", "TypeScript", "Firebase"]} href={siteConfig.links.scrambleTimer} action={t.projects.view} /><ProjectCard title="IntegraMath" subtitle={t.projects.mathTitle} description={t.projects.mathBody} image="/assets/integramath-macbook.png" alt={t.projects.mathAlt} technologies={["Next.js", "TypeScript", "HeroUI"]} href={siteConfig.links.integraMath} action={t.projects.view} /></div></div></section>;
}

export function Contact({ t }: { t: Content }) {
  const contacts = [
    { label: "LinkedIn", description: t.contact.linkedin, href: siteConfig.links.linkedin, icon: "devicon-linkedin-plain colored" },
    { label: "GitHub", description: t.contact.github, href: siteConfig.links.github, icon: "devicon-github-original" },
  ];
  return <section id="contact" className="section-space"><div className="container-shell"><div className="mx-auto max-w-2xl text-center"><p className="mb-3 text-sm font-semibold uppercase tracking-[.15em] text-blue-600">05 / {t.contact.title}</p><h2 className="section-title">{t.contact.title}</h2><p className="section-lead">{t.contact.intro}<br />{t.contact.second}</p></div><div className="mx-auto mt-9 grid max-w-3xl gap-4 sm:grid-cols-2">{contacts.map(({ label, description, href, icon }) => <a key={label} href={href} target="_blank" rel="noopener noreferrer" className="focus-underline card-surface group flex items-center gap-4 p-5 transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><i className={`${icon} technology-icon`} aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-slate-800">{label}</span><span className="mt-1 block truncate text-xs text-slate-500">{description}</span></span><ArrowRight size={16} className="text-slate-400 transition group-hover:translate-x-1 group-hover:text-blue-600" /></a>)}</div></div></section>;
}
